version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mysite
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ash123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  web:
    build: .
    command: ["uwsgi", "--ini", "uwsgi.ini"]
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_NAME: mysite
      DATABASE_USER: admin
      DATABASE_PASSWORD: ash123
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    ports:
      - "8000:80"
    depends_on:
      - web
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data:
